name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Get dependencies
        run: nix develop --command -- mix deps.get
      - name: Run tests
        run: nix develop --command -- mix test
      - name: Check fixture derivations
        run: nix flake check
